# Generated by Django 4.2.7 on 2023-11-30 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_logic', '0002_order_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='stripe_logic.order', verbose_name='заказ'),
        ),
    ]
