# Generated by Django 4.2.7 on 2023-11-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_logic', '0003_item_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='наименование')),
                ('value', models.PositiveIntegerField(default=10, max_length=2, verbose_name='размер скидки')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PD', 'оплачен'), ('PRD', 'обрабатывается'), ('FLD', 'проблема с оплатой')], default='PRD', max_length=3, verbose_name='статус'),
        ),
    ]
