# Generated by Django 4.2.7 on 2023-11-30 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_logic', '0004_discount_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(90)], verbose_name='размер скидки'),
        ),
    ]
